language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - tools
    - android-23
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-google_apis-23

env:
  global:
    - ANDROID_HOME=${TRAVIS_BUILD_DIR}/android-sdk
    - PATH=${ANDROID_HOME}/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools/:${PATH}

before_install:
  - ls /usr/local/
  - cp -R /usr/local/android-sdk-23.0.2 ./android-sdk
  - bin/sdkmanager --list || true
  - bin/sdkmanager --list --help || true
  - android list sdk -e || true
  - android list sdk -a -e || true
  - android list || true

before_script:
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a --tag google_apis
  - emulator -avd test -no-skin -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  ./gradlew checkstyle build connectedCheck
