language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - tools
    - android-23
    - android-25
    - sys-img-armeabi-v7a-google_apis-23

env:
  global:
    - ANDROID_HOME=${TRAVIS_BUILD_DIR}/android-sdk
    - PATH=${ANDROID_HOME}/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools/:/usr/local/android-sdk-24.0.2/tools/bin:${PATH}
    - EMULATOR="system-images;android-23;google_apis;armeabi-v7a"

before_install:
  - sdkmanager --list || true
  - sdkmanager --list --help || true
  - sdkmanager --uninstall "system-images;android-15;default;armeabi-v7a"
  - sdkmanager --uninstall "system-images;android-16;default;armeabi-v7a"
  - sdkmanager --uninstall "system-images;android-17;default;armeabi-v7a"
  - sdkmanager --uninstall "system-images;android-18;default;armeabi-v7a"
  - sdkmanager --uninstall "system-images;android-19;default;armeabi-v7a"
  - sdkmanager --uninstall "system-images;android-21;default;armeabi-v7a"
  - sdkmanager --uninstall "extras;google;google_play_services"
  - sdkmanager --uninstall "extras;android;support"
  - sdkmanager --uninstall "platforms;android-10"
  - sdkmanager --uninstall "platforms;android-15"
  - sdkmanager --uninstall "platforms;android-16"
  - sdkmanager --uninstall "platforms;android-17"
  - sdkmanager --uninstall "platforms;android-18"
  - sdkmanager --uninstall "platforms;android-19"
  - sdkmanager --uninstall "platforms;android-20"
  - sdkmanager --uninstall "platforms;android-21"
  - sdkmanager --uninstall "build-tools;21.1.2"
#  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "extras;android;m2repository"
  - echo yes | sdkmanager "extras;google;m2repository"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
  - sdkmanager --list || true
  - avdmanager list || true
  - echo "$PATH"
  - shopt -s dotglob
  - mkdir android-sdk
  - mv /usr/local/android-sdk-24.0.2/* android-sdk/
  - ls -Al
  - ls android-sdk -Al
  - ls android-sdk/tools -Al
  - ls android-sdk/tools/bin -Al
  - ls /home/travis/.android/ -Al
  - ls /home/travis/.android/avd/ -Al
  - ls /home/travis/.android/cache/ -Al
  - cat /home/travis/.android/repositories.cfg || true
  - echo 'Hello, world.' > repositories.cfg
  - cat /home/travis/.android/repositories.cfg || true
before_script:
#  - echo no | avdmanager create avd -n test -k "$EMULATOR" -f --abi armeabi-v7a
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a --tag google_apis
  - set QEMU_AUDIO_DRV=none
  - emulator -avd test -no-skin -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  ./gradlew checkstyle build connectedCheck
