language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.0
    - platform-tools
    - android-23
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-23

before_script:
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  ./gradlew checkstyle build connectedCheck
